### ISSUE TITLE
enhance asio detection error message

### ISSUE THREAD

**Issue by OznOg** [01org/parameter-framework#208]
for now asio detection made in cmake file generate an error when not detected. This error is maybe not really user friendly, would deserve to have a nice error message displayed.

**Comment by darshan934** [comment]
I am working on this.
Is there any specific text that you would like the error message to display?
Cheers

**Comment by dawagner** [comment]
Hello,

This issue was opened before there was any kind of custom error message regarding asio not being found. It has since been improved but we forgot to close this issue.

I'll close the issue and the associated PR; sorry about that. However, thank you for considering contributing to the project (may I ask how you came by it ?). If you would like improving the Parameter Framework in a similar way as fixing this issue, perhaps you could give us your opinion on the current build experience and feel free to raise any issue you come across.

Thanks again and sorry for not closing this earlier. I'll do some cleaning asap.
